server:
  port: 8086
spring:
  application:
    name: spring-cloud-practice-ribbon
  boot:
    admin:
      client:
        url: http://localhost:8899
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'