server:
  port: 8090
spring:
  application:
    name: spring-cloud-practice-stream
  rabbitmq:
    host: 192.168.56.1
  cloud:
    stream:
      bindings:
        greetingChannel: # binding 名稱，必須與 HelloBinding 定義相同
          destination: greetings # RabbitMQ 的 exchange 名稱