server:
  port: 8085
spring:
  application:
    name: spring-cloud-practice-zuul
  boot:
    admin:
      client:
        url: http://localhost:8899
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
zuul:
  routes:
    # {serviceId}: {expose url}
    spring-cloud-practice-feign: /feign/**
    spring-cloud-practice-ribbon: /ribbon/**