server:
  port: 8084
spring:
  redis:
    host: 192.168.56.1
  boot:
    admin:
      client:
        url: http://localhost:8899
#security:
#  oauth2:
#    client:
#      client-id: pwd_client
#      client-secret: 123456
#      user-authorization-uri: http://localhost:8089/oauth/authorize
#      access-token-uri: http://localhost:8089/oauth/check_token
#    resource:
#      id: my_test
#      user-info-uri: user-info # 沒有這個啟動會錯誤，Missing tokenInfoUri and userInfoUri and there is no JWT verifier key
#    authorization:
#      check-token-access: http://localhost:8089/oauth/check_token
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
feign:
  hystrix:
    enabled: true # 開啟 hystrix 熔斷器
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,hystrix.stream
my:
  identify: XD