server:
  port: 8084
spring:
  redis:
    host: 192.168.56.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
feign:
  hystrix:
    enabled: true # 開啟 hystrix 熔斷器
management:
  endpoints:
    web:
      exposure:
        include: refresh
my:
  identify: XD