server:
  port: 8089
spring:
  application:
    name: spring-cloud-practice-oauth2-server
  redis:
    host: 192.168.56.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
logging:
  level:
    com:
      rex:
        authorization:
          service:
            jdbc:
              rbac:
                mapper: debug